### ISSUE TITLE
Issues running the demo

### ISSUE THREAD

**Issue by ardoramor** [jaruba/node-vlcPlayer-demo#7]
I've read through all possible suggestions I could find on wcjs related forums but was not able to get the demo running. I've also seen related issues posted here but following them didn't resolve my problem.

The issue is **"%1 is not a valid Win32 application."**

I am using Windows 7 64-bit machine. I've extracted contents of the downloaded vlc-2.2.1 (32-bit release) release into the root of node-vlcPlayer-demo such that C:...\node-vlcPlayer-demo\vlc.exe is accessible. To be clear, the rest of the files are as expected (C:...\node-vlcPlayer-demo\package.json, etc).

I am planning to use NW.js. I have tried both 0.12.2 and 0.12.3 versions and the same issue occurs. I also tried Electron-Prebuilt but, again, the same issue occurs.

Before installing wcjs-player, I set the environment variables:

```
set npm_config_wcjs_runtime="nw"
set npm_config_wcjs_runtime_version="0.12.2"
set npm_config_wcjs_arch="ia32"
```

Then, I execute the following commands:

```
npm install nw@0.12.2 --save
npm install wcjs-player --save
.\node_modules\.bin\nw .
```

I'm seeing a lot of people having problems getting up and running with wcjs on Windows. To make sure I'm not confusing things, is my following understanding correct?
- wcjs-player (or rather webchimera.js part of it) installs as either 32 or 64 bit. 
- We use 32-bit VLC package as there is no VLC 64-bit pre-compiled package available (there is installation .exe available or you compile it yourself).
- So we make sure that webchimera.js and vlc are both compiled for 32-bit architecture
- We do that by specifying the `set npm_config_wcjs_arch="ia32"` env variable
- If we are planning to use NWjs to run the application, we should set `set npm_config_wcjs_runtime="nw"` and `set npm_config_wcjs_runtime_version="0.12.2"` (or the appropriate version such as 0.12.3) env variables.
- We also extract the contents of vlc package into the root of the project so that DLLs are found by the executable.

Additional questions:
- Why most suggestions are made to use NW version 0.12.2 and not 0.12.3?
- Does NW by default install 32 or 64-bit? Does the arch of NW need to be the same as of wcjs and vlc? If so, how can it be enforced to compile to 32-bit?

Sorry for the bunch of questions but I hope that if this issue gets resolved, many people will get their answers clearly spelled out. Thanks for any help!

**Comment by RSATom** [comment]
I'm trying reproduce your problem atm. But will try answer your questions before.

> wcjs-player (or rather webchimera.js part of it) installs as either 32 or 64 bit.

`wcjs-player` is pure JS module so could be run on both 32 and 64 bit engine

> We use 32-bit VLC package as there is no VLC 64-bit pre-compiled package available (there is installation .exe available or you compile it yourself).

VLC 64 bit is available: http://download.videolan.org/vlc/2.2.1/win64/
but I still recommend use 32 bit VLC on Windows as more widely used and thus most tested.

> So we make sure that webchimera.js and vlc are both compiled for 32-bit architecture

Yes, `WebChimera.js` and VLC should have same bitness. Same related to `NW.js`.

> We do that by specifying the  set npm_config_wcjs_arch="ia32"  env variable
> If we are planning to use NWjs to run the application, we should set  set npm_config_wcjs_runtime="nw"  and  set npm_config_wcjs_runtime_version="0.12.2"  (or the appropriate version such as 0.12.3) env variables.

it's necessary only for building `WebChimera.js` from sources ( i.e. if you take it from [git](https://github.com/RSATom/WebChimera.js) or [npm](https://www.npmjs.com/package/webchimera.js), directly or via dependency )
And you should set this env variables before `npm install`. If you want build `WebChimera.js` for different engine or engine version, you have to delete `node_modules` and do `npm install` again.

> We also extract the contents of vlc package into the root of the project so that DLLs are found by the executable.

Yes - but I have Idea why it could be wrong (I'll check). If you can't get it working, try place all VLC package content near the `WebChimera.js.node`

> Additional questions:
> Why most suggestions are made to use NW version 0.12.2 and not 0.12.3?

just because when `WebChimera.js` was initially released it was the latest version.

> Does NW by default install 32 or 64-bit?

it depends from bitness of your `node.js` if I remember correctly.

> Does the arch of NW need to be the same as of wcjs and vlc?

yes, all native modules should be same bitness.

> If so, how can it be enforced to compile to 32-bit?

`npm_config_wcjs_arch="ia32"` or `npm_config_wcjs_arch="x64"` for 64 bit build (but it will work only on Windows)

**Comment by jaruba** [comment]
_wow, i was writting just now too_

**Comment by RSATom** [comment]
ha-ha :)

**Comment by RSATom** [comment]
but maybe you could add something...

**Comment by ardoramor** [comment]
Thank you for the detailed answer!

I was able to get it working but only with all things compiled for x64 arch. From VLC files, I only dropped `plugins` directory, `libvlccore.dll`, `axvlc.dll`, `libvlc.dll`, and `npvlc.dll` into the root (from x64 release) and my player now works. Removing those libs breaks the player so I think that's the correct location to have them in.

I think my x86 builds were failing because there is no way to compile NW.js as x86 (saw an open issue on their gitlab but now cannot find it to link it). At least, that was the last point that I couldn't control as I was certain that WebChimera.js was compiling for x86 with `npm_config_wcjs_arch="ia32"` set and vlc libs were from x86 distribution.

**Comment by RSATom** [comment]
>  I only dropped  plugins  directory,  libvlccore.dll ,  axvlc.dll ,  libvlc.dll , and  npvlc.dll 

you could  `axvlc.dll`  and `npvlc.dll` too. And even some folders from `plugins`.

> there is no way to compile NW.js as x86

You don't need build `NW.js` yourself, just download it from http://nwjs.io/downloads/

**Comment by ardoramor** [comment]
I switched to Electron and have successfully built the app that integrates wcjs-player. I now can try out the 32 builds but currently have issues with nvm-windows. Will report back once I can get nvm under control.

**Comment by ardoramor** [comment]
Works great now with nvm switching to 32-bit nodejs and #31 resolution. Thanks!!
